### PR TITLE
Content improvements Robert

### PR DESCRIPTION
**Pull request by codeZeilen**

### CODE REVIEW

**Comment by codeZeilen** [comment]
@LinqLover Have you ever had the following problem in a build:

`[] in SBEScreenshotRecorder class>>doesNotUnderstand: #writeTo:building:`

Strikes me as kind of odd, given that all other tests ran successfully. (If you do not have any previous encounters with this bug: nevermind, I'll look into it :))

**Comment by LinqLover** [comment]
> @LinqLover Have you ever had the following problem in a build:
> 
> `[] in SBEScreenshotRecorder class>>doesNotUnderstand: #writeTo:building:`
> 
> Strikes me as kind of odd, given that all other tests ran successfully. (If you do not have any previous encounters with this bug: nevermind, I'll look into it :))

Sorry, I have not seen this before, but you could make sure that you have not loaded VB-Regex, see `#buildingSelectorPattern` (also notice the `#once` in this method). If this does not help, I can take a look at this tomorrow!

**Comment by codeZeilen** [comment]
Figured it out. The encoding of testShout require a weird escaping of the exclamation mark which leads to another test failure in StringTest. The debugger opens on the testShout test and we can not find our method... :) Will proceed to fix this now.

**Comment by LinqLover** [comment]
Oh yes, #25 ... 😆

**Pull request merged**
