### PR TITLE
New diagram files for Models and Collections chapter

### PR DESCRIPTION
**Pull request by codeZeilen**
@LinqLover the Models files are the stripped versions without the screenshot embedded. Feel free to rename them. I will continue on another PR.

### CODE REVIEW

**Comment by LinqLover** [comment]
@codeZeilen Why are there multiple files for each diagram? Can't we eliminate some of them by writing a proper CI script?

**Comment by LinqLover** [comment]
image

Hm ...

**Comment by codeZeilen** [comment]
> 
> 
> @codeZeilen Why are there multiple files for each diagram? Can't we eliminate some of them by writing a proper CI script?

Unfortunately not really, the visio file is the new ground truth but can not be used in the latex file. One of the svg and png files can be removed as soon as we settled for a good way to combine them with the screenshot.

**Comment by codeZeilen** [comment]
> 
> 
> image
> 
> Hm ...

Yes, the joys of LaTeX. Is that the png or the svg? As far as I remember transparent PNGs are only supported by the latest pdflatex version.

**Comment by LinqLover** [comment]
> Unfortunately not really, the visio file is the new ground truth but can not be used in the latex file.

https://sourceforge.net/projects/vdxtosvg/ or maybe http://dia-installer.de/vsd2svg/index.html.en might work, but I'm not sure whether it would be worth the effort.

> > image
> > Hm ...
> 
> Yes, the joys of LaTeX. Is that the png or the svg? As far as I remember transparent PNGs are only supported by the latest pdflatex version.

This is what you committed. :-) It looks as if the PNG version has won, I will prefer SVG anyway ... (Still strange because the CI uses a docker image for texlive)

Btw,  the legend arrows are missing in both PNG + SVG.

**Comment by LinqLover** [comment]
@codeZeilen Could you provide the diagrams in EPS/PDF, too? `includesvg` provides bad support on Windows and would be tricky on CI ... Otherwise, I'll use the PNG versions.

**Comment by LinqLover** [comment]
@codeZeilen Drafts are commited, but I need some EPS/PDF files before I can continue to align the Color-Buttons screenshots correctly ...

**Comment by LinqLover** [comment]
@codeZeilen Ready from my side, finally 😅

**Pull request merged**
