### PR TITLE
Migrate CI to GitHub Actions

### LINKED ISSUE #101: Migrate CI to GitHub Actions
_Originally posted by @codeZeilen in https://github.com/hpi-swa-lab/SqueakByExample-english/pull/97#discussion_r583013026_

### PR DESCRIPTION
**Pull request by LinqLover**
Closes #101 and closes #97.

This PR:

- migrates the entire CI pipeline from Travis CI to GitHub Actions, motivated by quota considerations, platform coolness & problems with Slack notifications as described in #97:

  image

- decouples single CI jobs for testing, @TEST assertions in TEX, and screenshot/PDF generation for a faster and more fine-granular feedback on GitHub (see above)

  * this involves a split-up of the `.smalltalk.ston` files and related scripts
  * also extracts internal SBE tests into a separate package called `SBE-Tests`

- implements support for GitHub Actions CI in Makefile and SmalltalkSources

- adds Slack notifications if a scheduled build (currently run once a week) fails:

  image

- provides PDF builds as artifacts on GitHub Actions instead of uploading them to Google Docs or GitHub Releases any longer:

  image

- fixes the `robustize-figures` mode (aka `DEBUG_FIGURES`) which was broken due to an update of the `graphicx` package and since 85b2080fb30b40c0292174dba1bfc4e924e8878a (thanks again to @AxelKrypton for helping with this issue!)

- updates the documentation in the README accordingly.

Please squash when merging.

### CODE REVIEW

**Comment by LinqLover** [comment]
Artifacts such as PDF are only accessible when all jobs have been completed, reported here: https://github.com/actions/upload-artifact/issues/181

**Comment by LinqLover** [comment]
Slack notifications are failing, opened an issue here: https://github.com/voxmedia/github-action-slack-notify-build/issues/46

**Comment by LinqLover** [comment]
Message from smalltalkCI:

```
Unable to parse Coveralls build data from /home/runner/.smalltalkCI/_builds/coveralls_build_data.json:
STONReaderError: At character 465: 'invalid escape character \i'
This is a smalltalkCI internal error. If the problem persists, please open an issue at https://github.com/hpi-swa/smalltalkCI/issues/new .
```

Todo: If this problem persists, let's create an issue.

**Comment by LinqLover** [comment]
Todos before merging:

- [ ] remove all debugging artifacts
- [ ] merge #103 and make sure to get a green bar afterward
- [ ] check both PDFs for hick-ups and version mismatches
- [ ] squash when merging

**Comment by codeZeilen** [comment]
Wow, nice work! Do you need a detailed review of specific parts or just a general, sweeping look? :)

**Comment by LinqLover** [comment]
> Wow, nice work @LinqLover ! Do you need a detailed review of specific parts or just a general, sweeping look? :)

Sweeping look should be enough :)

**Review by codeZeilen — APPROVED** [review]

**Pull request merged**
